### ISSUE TITLE
Tries to init but fails on Windows, but successful on Linux

### ISSUE THREAD

**Issue by thadguidry** [thadguidry/refine-groovy#2]
@wetneb do you have any idea what might be wrong or going on?

**Comment by wetneb** [comment]
Yes, you are indeed not registering any expression language in https://github.com/thadguidry/refine-groovy/blob/master/module/MOD-INF/controller.js

Compare this to
https://github.com/wetneb/refine-js/blob/master/module/MOD-INF/controller.js

**Comment by thadguidry** [comment]
@wetneb Hmm, where did things go wrong?
Before when bundled, I had this:  https://github.com/thadguidry/OpenRefine/commit/89858092d98b29ed78fa55e5243e0ef001d15706

Now, have this:
```
  // Register a new language parser for Groovy
  Packages.com.google.refine.expr.MetaParser.registerLanguageParser(
    "groovy",
    "Groovy",
    Packages.io.github.thadguidry.refinegroovy.GroovyEvaluable.createParser(),
    "value"
  );
```

which now as shown below cannot access the method but it could before when bundled?
```
Initializing refine-groovy extension
refine-groovy mount point is /extension/refine-groovy/ [*]
01:04:23.420 [         butterfly.module] Error initializing module refine-groovy by script function init() (924ms)
org.mozilla.javascript.EcmaError: TypeError: Cannot call property createParser in object [JavaPackage io.github.thadguidry.refinegroovy.GroovyEvaluable]. It is not a function, it is "object". (file:/F:/Downloads/openrefine-win-with-java-3.8.1/openrefine-3.8.1/webapp/extensions/refine-groovy/module/MOD-INF/controller.js#47)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4563)
```

**Comment by tfmorris** [comment]
I built this extension and unzipped it in my workspace extensions directory for the current development and it seemed to work fine, showing up in the Transform dialog's menu and accepting and processing Groovy syntax.

**Comment by thadguidry** [comment]
Well son of a gun.  Thanks @tfmorris it must have been my environment.  I will go back and test as well.

**Comment by thadguidry** [comment]
@tfmorris Any idea why I get the following error when I use the built version from my CI and download the release, install it into my workspace `/extensions` folder - but you don't see the same?  Can you try the release .zip package and see if you get this same error?

```
10:12:34.582 [                   refine] C:\Users\thadg\AppData\Roaming\OpenRefine (0ms)
Initializing refine-groovy extension
refine-groovy mount point is /extension/refine-groovy/ [*]
10:12:40.753 [         butterfly.module] Error initializing module refine-groovy by script function init() (6170ms)
org.mozilla.javascript.EcmaError: TypeError: Cannot call property createParser in object [JavaPackage io.github.thadguidry.refinegroovy.GroovyEvaluable]. It is not a function, it is "object". (file:/C:/Users/thadg/AppData/Roaming/OpenRefine/extensions/refine-groovy/module/MOD-INF/controller.js#47)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4563)
```

**Comment by tfmorris** [comment]
It would be very helpful to me if you could include versions when describing problems. It's not clear to me what version of the extension or of OpenRefine you're testing.

I tested refine-groovy 1.3.0, the latest of the three releases that I saw. It works with the latest HEAD from the master branch, but doesn't appear to work with OpenRefine 3.8.0, the latest release version that I have on my system. I didn't look into why.

Antonin did refactor the language parsers recently, but, as far as I remember, it shouldn't have affected this.

**Comment by thadguidry** [comment]
@tfmorris You are absolutely right and I should know better.  I am testing the refine-groovy 1.3.0 release against my workspace `/extensions` folder using OpenRefine 3.8.2

**Comment by thadguidry** [comment]
@wetneb 

I get this error:
```
org.mozilla.javascript.EcmaError: TypeError: Cannot call property createParser in object [JavaPackage io.github.thadguidry.refinegroovy.GroovyEvaluable]. It is not a function, it is "object". 
```
Yet our documentation about [Scripting Languages](https://openrefine.org/docs/technical-reference/writing-extensions#server-side-scripting-languages) says:
> The third is an object that implements the interface com.google.refine.expr.LanguageSpecificParser. 

So I have indeed put that object (not a function as the error states) there in third position:
https://github.com/thadguidry/refine-groovy/blob/495eab1354fc3e36d078adfefd79dcbaa7a77379/module/MOD-INF/controller.js#L46-L52

And my code below does implement that interface, no?  It `return new LanguageSpecificParser()` as seen on https://github.com/thadguidry/refine-groovy/blob/495eab1354fc3e36d078adfefd79dcbaa7a77379/src/main/java/io/github/thadguidry/refinegroovy/GroovyEvaluable.java#L23-L29

**Comment by wetneb** [comment]
I don't notice any obvious error. Generally this sort of error happens whenever the class / method cannot be found, so you might have packaging issues / name discrepancies or other things like that.

**Comment by thadguidry** [comment]
@ wetneb Looks like it is something with release 3.8.2?
1. If I debug run Refine from master branch in VSCode to launch OpenRefine, (keeping my same previously packaged refine-groovy in my workspace `/extensions` folder), then it works and inits that packaged refine-groovy without error!
2. I run OpenRefine 3.8.2 with Java embedded release,  (keeping my same previously packaged refine-groovy in my workspace `/extensions` folder), then I get that error.

So...hmm, it's a bug in 3.8.2 that is now resolved, I guess?

**Comment by thadguidry** [comment]
Let me try it with latest OpenRefine snapshot just to see.

**Comment by tfmorris** [comment]
On Sun, Sep 22, 2024 at 8:33 PM Thad Guidry ***@***.***>
wrote:

> So...hmm, it's a bug in 3.8.2 that is now resolved, I guess?
>
I suspect it's actually something to do with the packaging, as suggested by
Antonin, but I'm not sure what.

Although it failed to work with the 3.8.0 binary distribution, when I
checked out sources from the 3.8.0 tag, built and ran OpenRefine,
the Groovy extension worked fine. This suggests to me that it's not a
problem with the code, but some quirk of the packaging.

Tom

**Comment by thadguidry** [comment]
@tfmorris of my refine-groovy packaging?  or OpenRefine's Windows release package?

**Comment by tfmorris** [comment]
On Sun, Sep 22, 2024 at 8:51 PM Thad Guidry ***@***.***>
wrote:

> @tfmorris <https://github.com/tfmorris> of my refine-groovy packaging? or
> OpenRefine's Windows release package?
>
OpenRefine's release packaging on Windows & Mac. I used the same
refine-groovy zip file for all tests, with varying results.

**Comment by thadguidry** [comment]
Tested again with OpenRefine 3.9-SNAPSHOT version.  Same error as before when initializing the extension.

**Comment by wetneb** [comment]
I tried the extension with OpenRefine 3.9.0 on Linux, both built from the 3.9.0 tag and downloading the official release from GitHub. The Groovy extension worked in both cases.

Getting it to compile for OpenRefine 3.9 requires a small change to the pom.xml which I'll contribute separately.

**Comment by thadguidry** [comment]
Still fails with 1.3.2 Release built for OpenRefine 3.9.0 and using Windows
Yet @wetneb says it works on Linux just fine?
Wondering if it's Butterfly somehow misconstruing the path needed on Windows but is happy on Linux?
Asked a few LLM's and they say that as long as the paratheses are found at the end of the call like  `Packages.io.github.thadguidry.refinegroovy.GroovyEvaluable.createParser(),` it will use it as a function, not an object, and if it still complains then it's an issue with referencing... which would be something within Butterfly's changes recently that somehow affect Windows only?

```
07:18:35.580 [                   refine] Starting OpenRefine 3.9-SNAPSHOT [TRUNK] ... (3173ms)
07:18:35.581 [                   refine] Initializing FileProjectManager with data dir: C:\Users\thadg\AppData\Roaming\OpenRefine (0ms)
Initializing refine-groovy extension
refine-groovy mount point is /extension/refine-groovy/ [*]
07:18:40.882 [         butterfly.module] Error initializing module refine-groovy by script function init() (5301ms)
org.mozilla.javascript.EcmaError: TypeError: Cannot call property createParser in object [JavaPackage io.github.thadguidry.refinegroovy.GroovyEvaluable]. It is not a function, it is "object". (file:/C:/Users/thadg/AppData/Roaming/OpenRefine/extensions/refine-groovy/module/MOD-INF/controller.js#47)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4692)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4673)
```

**Comment by thadguidry** [comment]
Resolved! My local dev environment under "master" branch was actually a bit corrupted I guess?  Using `git clean -fdx` fixed this issue.  Was able to compile master branch (without extraneous files) and then extract the **refine-groovy** extension into the same folder I was using before... and it worked!
